language: cpp
compiler:
  - gcc
  - clang
before_install:
  # g++ 4.9.0
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

  # cmake 3.1.0
  - cd /tmp
  - wget http://www.cmake.org/files/v3.1/cmake-3.1.0.tar.gz
  - tar xzf cmake-3.1.0.tar.gz
  - cd cmake-3.1.0
  - ./configure
  - make
  - sudo make install
  - /usr/local/bin/cmake --version

  # system
  - sudo apt-get update -qq
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq libboost1.48-dev libyajl-dev libxml2-dev libxqilla-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
before_script:
  - BUILD_DIR=`pwd`/builds
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
script:
  - cd ${BUILD_DIR}
  - make
