language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq libboost1.48-dev libyajl-dev libxml2-dev libxqilla-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo apt-get install -qq cmake-2.8.11
before_script:
  - BUILD_DIR=`pwd`/builds
  - mkdir -p ${BUILD_DIR}
  - cd ${BUILD_DIR}
  - cmake ..
script:
  - cd ${BUILD_DIR}
  - make
